### ISSUE TITLE
VF_AUTOADDPROP by default?

### ISSUE THREAD

**Issue by andrei-markeev** [YasserAsmi/jvar#14]
Hi,

I was just wondering, are there any reasons why VF_AUTOADDPROP flag is not ticked by default?
It doesn't break anything, and it is JavaScript-compatible.
I think it can be switched on manually, but this introduces a lot of boilerplate.

So my question is, can it be made on by default, or at least can we have a separate build configuration where it is default?

**Comment by YasserAsmi** [comment]
Good question.  It is definitely easier with this is on by default.  I was initially thinking that it is a weakness in JS (ie not safe)...  May be a one time setting in your app would be a good solution?

**Comment by andrei-markeev** [comment]
One time setting is definitely OK with me, but the app in question is developed by many people, so it would be nice if it was supported in some way by how the library itself is compiled.

So that I could say: ok guys, please take this library and compile it with these flags.

Hence I propose a separate cmake option, like this:
```
cmake -DAUTOADDPROP ..
```

What do you say?

**Comment by YasserAsmi** [comment]
Yeah that might be ok
I just don't know enough cmake to do that.  If you want to do that it will be great :)

Btw. We might need another cmake config for c++ 11.  Alex's change adds the c++11 compiler flag. Would be better to wrap that in a setting.

(mobile)

On Dec 19, 2015, at 1:55 AM, Andrei Markeev <notifications@github.com<mailto:notifications@github.com>> wrote:


One time setting is definitely OK with me, but the app in question is developed by many people, so it would be nice if it was supported in some way by how the library itself is compiled.

So that I could say: ok guys, please take this library and compile it with these flags.

Hence I propose a separate cmake option, like this:

cmake -DAUTOADDPROP ..


What do you say?

-

**Comment by andrei-markeev** [comment]
Sure, I can do that! And I will review changes from Alex and will make sure that there are no conflicts.
